# Generated by Django 4.2 on 2023-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modellog",
            name="input",
            field=models.CharField(max_length=300),
        ),
    ]
