# Generated by Django 4.2 on 2023-04-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_modellog_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="modellog",
            name="celery_task_uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="modellog",
            name="completed_at",
            field=models.DateTimeField(
                help_text="Datetime field when the task was completed in UTC",
                null=True,
                verbose_name="Completed DateTime",
            ),
        ),
        migrations.AddField(
            model_name="modellog",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="modellog",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILURE", "FAILURE"),
                    ("PENDING", "PENDING"),
                    ("RECEIVED", "RECEIVED"),
                    ("RETRY", "RETRY"),
                    ("REVOKED", "REVOKED"),
                    ("STARTED", "STARTED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                default="PENDING",
                editable=False,
                help_text="Current state of the task being run",
                max_length=50,
                verbose_name="Task State",
            ),
        ),
        migrations.AlterField(
            model_name="modellog",
            name="error_log",
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="modellog",
            name="input",
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name="modellog",
            name="output",
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
